### ISSUE TITLE
client/post form-params array

### ISSUE THREAD

**Issue by WeweTom** [dakrone/clj-http#241]
I use client/post the data below to a PHP script

```
:form-params {:foo ["bar" "ffff"]}
```

but on the PHP side I only got 

```
POST['foo']   =  "ffff"
```

what I expect is 

```
POST['foo']   = [0=>"bar", 1=> "ffff"]
```

what I'm wrong?

**Comment by joegallo** [comment]
I believe you're running into an issue with how PHP treats parameters with the same name. [See here for more.](http://stackoverflow.com/questions/4951448/how-to-use-get-to-get-multiple-parameters-using-the-same-name-in-php)

By my read of the above, you'd need to pass your parameter like this:

    :form-params {"foo[]" ["bar" "ffff"]}

for things to work the way you'd want, but that's purely due to the way PHP handles things, and not due to anything you're doing 'wrong' on the client side.

**Comment by WeweTom** [comment]
Yes , you are right , thanks!

**Comment by dakrone** [comment]
Great, I am going to close this then, thanks @joegallo
