### ISSUE TITLE
Private functions?

### ISSUE THREAD

**Issue by atroche** [dakrone/clj-http#244]
Hey @dakrone, from reading the source I can't tell which functions are supposed to be internally used and which are supposed to be exposed to the consumer of `clj-http`. How would you feel if I put a PR that converted some fairly clear candidates to being private?

**Comment by dakrone** [comment]
HI @atroche do you know what functions in particular? A lot of the functions are left intentionally public so that people can rewrite/reuse some of the internals for their own use, but I could see some of them being made private.

Maybe better docstrings would help also, to indicate whether a function is intended to be internal only or not.

**Comment by dakrone** [comment]
Closing with no feedback since January.
