### ISSUE TITLE
is there a way to cancel ongoing request, or something like that? like request timeout

### ISSUE THREAD

**Issue by xudifsd** [dakrone/clj-http#251]
I want to do request under some timeout, but it seems there're only `socket-timeout` and `conn-timeout`.

What I really want is some request timeout: if haven't got response, then cancel this request. Is there a way to do this?

**Comment by dakrone** [comment]
There currently isn't a way to do this, I'm not sure whether the Apache HTTP client exposes anything for this either

**Comment by joegallo** [comment]
I suppose you could always slap your http/get into a future and then do the timeout-y version of deref. If you timed out, then you could future-cancel.

**Comment by xudifsd** [comment]
@joegallo Well, I used core.async timeout to do this, but it doesn't provide cancelation functionality

**Comment by lorettahe** [comment]
I'm also looking for a similar functionality. I think HttpUriRequest interface does expose an 'abort' method. Could we perhaps use this? 
http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/methods/HttpUriRequest.html

**Comment by paraseba** [comment]
How about .setConnectionRequestTimeout in RequestConfig.Builder? 

https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/RequestConfig.Builder.html#setConnectionRequestTimeout(int)

Interested on a patch for this?

**Comment by RutledgePaulV** [comment]
This is particularly valuable if you're using the http client for long-lived requests whose need for a result might be aborted mid-request by a user. Right now without a supported way to abort a request and return it to the connection pool that connection is basically out-of-commission since there's still data in the pipe and keep-alive.

I've hit this issue in a web application that proxies PDFs through to the user's browser (after undergoing some security checks). I had just been handing off an input stream to ring to write to the output stream but I was finding that after a user canceled their request (because maybe it was a large PDF and they decided they're not interested any more) that my connection pool was quickly depleted and the entire app locks up.

I'm looking now for a way to get a handle on the connection so I can release it myself in the event of a client-abort.

**Comment by RutledgePaulV** [comment]
FWIW here's my hack to get around the fact that apache likes to "drain" the entire in-flight response before returning the connection to the pool. When you close the input stream in the clj-http response it normally does a graceful "close" on the input stream provided by apache http (and indeed apache doesn't expose the abort directly), but in this case I'm triggering a hard "abortConnection" by throwing an IOException. This way it doesn't try to drain the request before making it available to the connection pool again (which, if there's a lot of data, might take a while).

```clojure
(alter-var-root #'clj-http.core/coerce-body-entity
  (fn [_]
    (fn [^ResponseEntityProxy http-entity conn-mgr ^CloseableHttpResponse response]
      (if http-entity
        (proxy [FilterInputStream]
               [^InputStream (.getContent http-entity)]
          (close []
            (try
              (try
                (.eofDetected http-entity
                  (proxy [InputStream] []
                    (read [] -1)
                    (close []
                      (throw (IOException. "Please, don't drain my request.")))))
                (catch Exception ignored nil))
              (let [^InputStream this this] (proxy-super close))
              (finally
                (when (instance? CloseableHttpResponse response)
                  (.close response))
                (when-not (conn/reusable? conn-mgr)
                  (conn/shutdown-manager conn-mgr))))))
        (when-not (conn/reusable? conn-mgr)
          (conn/shutdown-manager conn-mgr))))))
```

**Comment by dakrone** [comment]
I added a better way to abort the request along with the future and some docs for it, let me know if this doesn't work for you and I'll be happy to revisit it.

**Comment by RutledgePaulV** [comment]
Changes look good if using async. In my case I was handing off a synchronous stream to a downstream connection (a browser). When that connection closed I wanted to abort the http request instead of waiting for it to finish downloading from the upstream. I added that ability to the "close" method of the input stream. 

There's a good chance I could refactor that code to be asynchronous and use the official mechanism now instead of my hack :) thanks.
