### ISSUE TITLE
Does 3.0.0 have breaking changes to the API?

### ISSUE THREAD

**Issue by atroche** [dakrone/clj-http#319]
Hi @dakrone, are you using [the convention](http://semver.org/) where a bump in the major version number (e.g. from 2.x to 3.x) means there are breaking changes to the API? If so, what are they? If not, great =)

**Comment by elegoff** [comment]
More generally I would find it useful if there was something like a release note which would highlight major features/bug fixes of any given version

**Comment by dakrone** [comment]
2.x -> 3.x did have breaking changes, due to the change from the deprecated to the non-deprecated Apache APIs. I bumped the major version to signify this.

Unfortunately, I have been very bad at documenting breaking changes, features, and other things :(

Currently the only way is to look at the commit log, I will try to be better going forward (I should probably add it to a contribution guide)

**Comment by rymndhng** [comment]
@dakrone would you be interested in PRs to clean up the README?

I propose removing the section "Towards 3.x" and changing it to "Upgrading from Pre-3.x Versions". I know the redirects docs could be improved here.

**Comment by dakrone** [comment]
> @dakrone would you be interested in PRs to clean up the README?

I'm *definitely* interested in PRs to clean up the readme!

**Comment by rymndhng** [comment]
Here's what I've found from skimming so far

Notable Changes:
- CHANGED: re-written middleware using apache http client 4.5
- CHANGED: a2c31f5 Fix retry-handler to be added in correct place
- CHANGED: 983508f POST Mutipart: Use charset "UTF-8" instead of "ASCII" as default charset to support internationalization
- REMOVED :save-request
- ADDED: HttpRequestInterceptor support 155bd23
- ADDED: protocol-version and reason-phrase f430517
- ADDED: support for async HTTP requests (like Ring) 44d10ec
- ADDED: support for different multi-param encoding (:repeating, :array, :indexed) cddeb3e
- ADDED: aec7dd1 Add unparse function
- ADDED: graceful-redirect strategy
- ADDED: feb3c48 Allow RequestConfig and HttpClientContext to be injected

**Comment by dakrone** [comment]
@rymndhng feel free to commit those to `changelog.org`! That would be great!
