### ISSUE TITLE
Still looking for help?

### ISSUE THREAD

**Issue by ahgardner** [dakrone/clj-http#321]
Your Readme asks for help to get 3.0 debugged, but now we are at 3.1.1.  Are the tests all working now?  I got no errors, but two fails, due to "http://aorecuf892983a.com" not found.

**Comment by dakrone** [comment]
@ahgardner sounds like your DNS might be hijacking things (http://aorecuf892983a.com should fail due to DNS resolution failure unless your ISP is hijacking it).

The tests are working now, but there is a lot of work still to be done, for instance, the connection manager code needs to be simplified, and another pass needs to be done to see if any more deprecated APIs are in use, so any help is appreciated!

Additionally, there are things like reusing the httpclient between requests (perhaps only when a connection manager is used) that need to be worked out.

**Comment by 7h3kk1d** [comment]
Should I try putting up a pr changing the readme from the current fix tests help wanted approach?

**Comment by dakrone** [comment]
@7h3kk1d that'd be great!
