### ISSUE TITLE
trace-redirects not populated

### ISSUE THREAD

**Issue by ray1729** [dakrone/clj-http#326]
Hi, it appears with the move to 3.X that the `:trace-redirects` response field is no longer correctly populated. It turns out that, when you use Apache HTTP client's `DefaultRedirectStrategy` the `wrap-redirects` middleware is redundant. I haven't included a pull request here as I'm not sure how you'd like to proceed. One possibility would be to maintain the existing use of `DefaultRedirectStrategy` and remove `wrap-redirects` and `follow-redirect` from `clj-http.client`. You could then modify `clj-http.core/request` to get the redirect locations from the context, something like: 
`(.getAll (.getAttribute context HttpClientContext/REDIRECT_LOCATIONS))`

**Comment by Abhiroop** [comment]
@ray1729 Hi I am looking into this issue. I am looking into this issue. It would be helpful if you could give me an example of a site which redirects so I can reproduce the issue.

**Comment by ray1729** [comment]
For me, http://www.google.com/ issues a redirect. For example, with clj-http 2.0.1:

    user=> (:trace-redirects (clj-http.client/get "http://www.google.com"))
    ["http://www.google.com" "http://www.google.co.uk/?gfe_rd=cr&ei=WIKOV-WANtLCaOCfo6gD"]

but with 3.1.0:

    user=> (:trace-redirects (clj-http.client/get "http://www.google.com"))
    ["http://www.google.com"]

**Comment by andrew-potgieter** [comment]
I have found a temporary workaround which is to disable the `DefaultRedirectStrategy` using the `:redirect-strategy :none` option which allows the middleware to kick in.

```
=> (:trace-redirects (clj-http.client/get "http://www.google.com" {:redirect-strategy :none}))
["http://www.google.com" "http://www.google.co.uk/?gfe_rd=cr&ei=pIoGWPvAFcn07AbTlqjACg"]
```

However, the `DefaultRedirectStrategy` seems to have also broken the `:max-redirects` functionality as in this example: 

```
=> (:trace-redirects (get "http://www.google.com" {:max-redirects 0 :throw-exceptions true}))
["http://www.google.com"]
```

In the above case I know there is a redirect so I should have got the error message.

Using the workaround this does behave as expected:

```
=> (:trace-redirects (get "http://www.google.com" {:max-redirects 0 :throw-exceptions true :redirect-strategy :none}))
ExceptionInfo Too many redirects: 1  slingshot.support/stack-trace 
```
 
So, if we deprecate the `wrap-redirects` middleware, would it be a good idea to make sure the functionality of its options is covered elsewhere? In which case should we not just remove the middleware entirely?
I quite like the middleware architecture so that seems a shame but thats just me. :)
Could it be an option to integrate the redirect middleware with the underlying libraries redirect strategy so as to keep the middleware.

**Comment by RokLenarcic** [comment]
I also ran into this using `GET` on `http://klapa.simobil.net/klapa/send.php`, which redirects two times. The contents returned are correct (they are of the redirect), but the `:trace-redirects` is wrong.

**Comment by andrew-potgieter** [comment]
Thanks to the example from @RokLenarcic I cleared up the case with the `:max-redirects`. It seems that the apache library assumes that a max redirects of 0 does not count. This makes sense since it is the same as disabling the redirects. So using the above example it seems correct:

```
clj-http.client> (head "http://klapa.simobil.net/klapa/send.php" {:max-redirects 1 :throw-exceptions true})
RedirectException Maximum redirects (1) exceeded  org.apache.http.impl.execchain.RedirectExec.execute (RedirectExec.java:117)
```

**Comment by rymndhng** [comment]
Is this issue closable now that that #361 is in?

**Comment by dakrone** [comment]
I believe so, thanks @rymndhng
