### ISSUE TITLE
How to deal with (expected) html error responses.

### ISSUE THREAD

**Issue by jellelicht** [dakrone/clj-http#488]
I am interacting with a REST service that sends a 429 response with html body when some rate limit is exceeded. This is to be expected, as I need some form of backpressure to make sure I don't flood the service with requests.

I use the `:unexceptional-status` key in my request to make sure no exception is thrown if this happens, but sadly this also makes clj-http try to parse the html body as json. This leads to an exception:
```
1. Caused by com.fasterxml.jackson.core.JsonParseException
   Unexpected character ('<' (code 60)): expected a valid value
   (number, String, array, object, 'true', 'false' or 'null') at
```

For the sake of completeness, I want to wait for 1 second after receiving a 429 and trying again, up to a maximum of 4 times. Is what I want possible, or should I hack around with clj-http internals?

**Comment by dakrone** [comment]
> I use the `:unexceptional-status` key in my request to make sure no exception is thrown if this happens, but sadly this also makes clj-http try to parse the html body as json.

This sounds like a bug, do you have the invocation of clj-http where you pass this in so I can try to reproduce it?

> I want to wait for 1 second after receiving a 429 and trying again, up to a maximum of 4 times. Is what I want possible, or should I hack around with clj-http internals?

Definitely, I have had great luck in the past combining clj-http and https://github.com/joegallo/robert-bruce to perform the retries.

**Comment by jellelicht** [comment]
That is going to be a bit hard, as it involves an API with my access token (not to mention that it only happens once I have used up my allowance of unfettered requests for that hour).

I could try to record the request (and response) using something like Fiddler, strip out all sensitive parts, and upload that. Would that be helpful?

**Comment by dakrone** [comment]
> That is going to be a bit hard, as it involves an API with my access token (not to mention that it only happens once I have used up my allowance of unfettered requests for that hour).

It doesn't have to be exhaustive, I mostly wanted to know about the options passed to the method, some pseudocode like

```clj
(http/post "url" {:body foo :unexceptional-status #{201 208 200} :as :stream})
```

(or however you invoked it) would be helpful for me to track this down

**Comment by aterweele** [comment]
Hi @jellelicht ! I think that `:as :json` assumes that the body will always contain JSON, which is not the case here. This is how I would approach the situation:

```clojure
(defmethod clj-http.client/coerce-response-body ::json-on-success
  [_ {:keys [status] :as resp}]
  (update resp
          :body
          (fn [body]
            (if (clj-http.client/unexceptional-status? status)
              (->> body
                   clojure.java.io/reader
                   cheshire.core/parse-stream)
              (slurp body)))))
```

Now, the body of a 429 response will not parsed as JSON:

```clojure
(let [server
      (ring.adapter.jetty/run-jetty
       (constantly
        {:status 429
         :body "<h1>hello!</h1>"})
       {:join? false
        :port 8080})]
  (try
    (-> "http://localhost:8080/"
        (clj-http.client/get
         {:as ::json-on-success
          :unexceptional-status
          (some-fn clj-http.client/unexceptional-status?
                   #{429})})
        (select-keys #{:status :body}))
    (finally (.stop server))))
;; => {:status 429, :body "<h1>hello!</h1>"}
```

and anything that `clj-http.client/unexceptional-status?` considers successful gets parsed as JSON:

```clojure
(let [server
      (ring.adapter.jetty/run-jetty
       (constantly
        {:status 200
         :body (cheshire.core/generate-string {:foo "bar"})})
       {:join? false
        :port 8080})]
  (try
    (-> "http://localhost:8080/"
        (clj-http.client/get
         {:as ::json-on-success
          :unexceptional-status
          (some-fn clj-http.client/unexceptional-status?
                   #{429})})
        (select-keys #{:status :body}))
    (finally (.stop server))))
;; => {:status 200, :body {"foo" "bar"}}
```

**Comment by jellelicht** [comment]
Wow @aterweele thanks a bunch! I'll have to try this out early next week, but this seems like what I need indeed. :+1:

**Comment by atw-gr** [comment]
> I think that `:as :json` assumes that the body will always contain JSON

I think that while my advice stands, the situation is a little more nuanced than what I thought above. Consider:

```clojure
(let [server
      (ring.adapter.jetty/run-jetty
       (constantly
        {:status 429
         :body "<h1>hello!</h1>"})
       {:join? false
        :port 8080})]
  (try
    (-> "http://localhost:8080/"
        (clj-http.client/get
         {:as :json
          :coerce :unexceptional
          :unexceptional-status
          (some-fn clj-http.client/unexceptional-status?
                   #{429})})
        (select-keys #{:status :body}))
    (finally (.stop server))))
;; throws the exception that @jellelicht wrote about
```

The [implementation of `clj-http.client/coerce-response-body` for `:as :json`](https://github.com/dakrone/clj-http/blob/3.10.0/src/clj_http/client.clj#L538) calls [`clj-http.client/coerce-json-body`](https://github.com/dakrone/clj-http/blob/3.10.0/src/clj_http/client.clj#L469) which uses [`clj-http.client/can-parse-body?`](https://github.com/dakrone/clj-http/blob/3.10.0/src/clj_http/client.clj#L447) to determine whether to parse or not.

`can-parse-body?` respects [`:coerce`](https://github.com/dakrone/clj-http#output-coercion). The default of `:coerce` (which I use in my examples above) is to use `clj-http.client/unexceptional-status-for-request?`, and because I specify in my request that a 429 is unexceptional, the body of a 429 response gets parsed as JSON.

Given that, I might submit a PR to amend this line in the README:

> JSON coercion defaults to only an “unexceptional” statuses, meaning status codes in the #{200 201 202 203 204 205 206 207 300 301 302 303 304 307} range.

to something like

> JSON coercion defaults to only coerce the body of a response with an unexceptional status, see `:unexceptional-status`

**Comment by aterweele** [comment]
> I think that `:as :json` assumes that the body will always contain JSON

I think that while my advice stands, the situation is a little more nuanced than what I thought above. Consider:

```clojure
(let [server
      (ring.adapter.jetty/run-jetty
       (constantly
        {:status 429
         :body "<h1>hello!</h1>"})
       {:join? false
        :port 8080})]
  (try
    (-> "http://localhost:8080/"
        (clj-http.client/get
         {:as :json
          :coerce :unexceptional
          :unexceptional-status
          (some-fn clj-http.client/unexceptional-status?
                   #{429})})
        (select-keys #{:status :body}))
    (finally (.stop server))))
;; throws the exception that @jellelicht wrote about
```

The [implementation of `clj-http.client/coerce-response-body` for `:as :json`](https://github.com/dakrone/clj-http/blob/3.10.0/src/clj_http/client.clj#L538) calls [`clj-http.client/coerce-json-body`](https://github.com/dakrone/clj-http/blob/3.10.0/src/clj_http/client.clj#L469) which uses [`clj-http.client/can-parse-body?`](https://github.com/dakrone/clj-http/blob/3.10.0/src/clj_http/client.clj#L447) to determine whether to parse or not.

`can-parse-body?` respects [`:coerce`](https://github.com/dakrone/clj-http#output-coercion). The default of `:coerce` (which I use in my examples above) is to use `clj-http.client/unexceptional-status-for-request?`, and because I specify in my request that a 429 is unexceptional, the body of a 429 response gets parsed as JSON.

Given that, I might submit a PR to amend this line in the README:

> JSON coercion defaults to only an “unexceptional” statuses, meaning status codes in the #{200 201 202 203 204 205 206 207 300 301 302 303 304 307} range.

to something like

> JSON coercion defaults to only coerce the body of a response with an unexceptional status, see `:unexceptional-status`

**Comment by dakrone** [comment]
> Given that, I might submit a PR to amend this line in the README

Please do, that would be great!

**Comment by jellelicht** [comment]
This works very well, by the way! Thanks for the advice :-)
