### ISSUE TITLE
Unable to get aspx pages

### ISSUE THREAD

**Issue by sooheon** [dakrone/clj-http#491]
I'm scraping a bunch of sites, and noticed that .aspx sites consistently fail get requests:
```
(client/get "https://www.thesundevils.com/rss_feeds.aspx")
=> ExceptionInfo clj-http: status 404  slingshot.support/stack-trace (support.clj:201)
*e
=>
#error{:cause "clj-http: status 404",
       :data {:request-time 201,
              :repeatable? false,
              :protocol-version {:name "HTTP", :major 1, :minor 1},
              :streaming? false,
              :chunked? false,
              :type :clj-http.client/unexceptional-status,
              :reason-phrase "Not Found",
              :headers {"Server" "Microsoft-IIS/8.5",
                        "Date" "Fri, 10 May 2019 11:06:10 GMT",
                        "Connection" "close",
                        "Content-Length" "0"},
              :orig-content-encoding nil,
              :status 404,
              :length 0,
              :body "",
              :trace-redirects []}
...
```

This happens for all aspx pages I'm scraping, and it's always a 404, even though curl and visiting the page in a browser show the expected xml.

**Comment by dakrone** [comment]
So `clj-http` doesn't do anything that would cause aspx pages not to return, and since the server is returning a 404 I suspect they are doing something silly based on the user agent. The URL works in a web browser but when I use `curl` I get an empty response back.

I notice that this *does* work when I pretend to be Firefox instead of curl or clj-http:

```clj
(http/get "https://thesundevils.com/rss_feeds.aspx" 
          {:headers
            {:user-agent
             "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"}})
```

So I'm 99% sure this is a server issue rather than a clj-http bug.

**Comment by sooheon** [comment]
Thanks, that is indeed correct :)
