### ISSUE TITLE
Failed to disable Cookie rejected warning

### ISSUE THREAD

**Issue by iGEL** [dakrone/clj-http#497]
This is related to #444 and #390 I believe, but the solutions proposed there don't work for my case. In my case, the cookie has a `domain` set, which is not the host I make the request to. So it's probably the correct behavior to reject the cookie.

But I don't care about the cookies and would like to get rid of the warning it produces, which is

`
WARNING: Cookie rejected [JSESSIONID="EC53F...26063", version:0, domain:subdomain-a.example.com, path:/, expiry:null] Illegal 'domain' attribute "subdomain-a.example.com". Domain of origin: "subdomain-b.example.com"
`

I tried both `{:cookie-policy :standard, :decode-cookies false}` and the `(http/with-middleware (remove #(= % clj-http.cookies/wrap-cookies) http/default-middleware)` hack, but the warning is still there.

**Comment by rymndhng** [comment]
Hey there! 

It appears the warning is coming from the underlying Apache HTTPClient library. The error seems reasonably important to surface because the web server is trying to set an invalid set of cookies.

I think the options you specified won't help because the Apache HTTPClient library processes the cookies before the clojure wrapper has an opportunity to transform it.

I can think of two ways to make the message disappear:

1. Silence the logger by configuring your logging library. See [ResponseProcessCookie.java](https://github.com/apache/httpcomponents-client/blob/37c80064726f0e4ae547c14ad73129483a81a67c/httpclient5/src/main/java/org/apache/hc/client5/http/protocol/ResponseProcessCookies.java#L114-L117)

2. If you don't care about cookies at all, you can completely remove it by configuring the client. See these instructions: https://github.com/dakrone/clj-http#modifying-apache-specific-features-of-the-httpclientbuilder-and-httpasyncclientbuilder. It looks like stackoverflow has this as a solution as well. See [link](https://stackoverflow.com/questions/7459279/httpclient-warning-cookie-rejected-illegal-domain-attribute).

**Comment by iGEL** [comment]
Thank you, I disabled cookies like this:
```clojure
(ns x
  (:import (org.apache.http.impl.client HttpClientBuilder)))

(defn- cookie-disabler [^HttpClientBuilder builder
                           request]
 (when (:disable-cookies request)
    (.disableCookieManagement builder)))

(http/get "http://google.com" {:http-builder-fns [cookie-disabler], disable-cookies true})
```
